/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

/**
 *
 * @author Wilhams Gomes
 */
public class Intro3 extends javax.swing.JFrame {

    /**
     * Creates new form Intro3
     */
    public Intro3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_pular = new javax.swing.JLabel();
        lbl_intro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_pular.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        lbl_pular.setText("Iniciar o jogo");
        lbl_pular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_pular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pularMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_pular, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 170, 30));

        lbl_intro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_intro/intro3.jpg"))); // NOI18N
        getContentPane().add(lbl_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 452));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_pularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pularMouseClicked

        Nvl1 obj = new Nvl1();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_lbl_pularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Intro3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_intro;
    private javax.swing.JLabel lbl_pular;
    // End of variables declaration//GEN-END:variables
}
